# TURNOUT-CONTROL-1.yml
#
# This ESPHome config controls 8 model railroad turnouts using l298 H-bridges.
# Each turnout is controlled by two GPIO outputs (A and B) and triggered by MQTT messages.
#
# MQTT topics: track/turnout/TO-1-N (N=1..8), payload: 'THROWN' or 'CLOSED'
#
# Hardware: ESP32 (32-pin), outputs mapped to GPIO pins below.
#
# Usage:
#  - Send MQTT message to topic 'track/turnout/TO-1-N' with payload 'THROWN' or 'CLOSED'.
#  - Each command pulses the turnout for the time set in 'turnout_pulse_ms'.

#pin assignments
# L2981 = 19R, 18B, 5Y, 17W
# L2982 = 16R, 4B, SPACE, 2Y, 15W    #space means the 4 wire connector needs to have one of the pins split off since the pins are adjacent.
# L2983 = 32R, 33B, 25Y, 26W
# L2984 = 27R, 14B, 12Y,13W

#
substitutions:
  esp_id: "1" # Controller number
  turnout_pulse_ms: "1000ms" # Pulse duration for turnout coil

esphome:
  name: tc-${esp_id}

esp32:
  board: esp32dev
  framework:
    type: arduino

ota:
  password: !secret ota_password
  platform: esphome

wifi:
  networks:
    - ssid: !secret wifi_ssid_iot
      password: !secret wifi_password_iot
    - ssid: !secret wifi_ssid_santafe
      password: !secret wifi_password_santafe
  ap:
    ssid: !secret fallback_ssid
    password: !secret fallback_password

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

  # Listen for turnout commands on MQTT and operate outputs accordingly
  on_message:
    # Turnout 1
    - topic: "track/turnout/TO-1-1"
      then:
        - lambda: |-
            auto payload = x.c_str();
            if (strcmp(payload, "THROWN") == 0) {
              id(turnout_1_a).turn_on();
              id(turnout_1_b).turn_off();
            } else if (strcmp(payload, "CLOSED") == 0) {
              id(turnout_1_a).turn_off();
              id(turnout_1_b).turn_on();
            }
        - delay: ${turnout_pulse_ms}
        - output.turn_off: turnout_1_a
        - output.turn_off: turnout_1_b
    # Turnout 2
    - topic: "track/turnout/TO-1-2"
      then:
        - lambda: |-
            auto payload = x.c_str();
            if (strcmp(payload, "THROWN") == 0) {
              id(turnout_2_a).turn_on();
              id(turnout_2_b).turn_off();
            } else if (strcmp(payload, "CLOSED") == 0) {
              id(turnout_2_a).turn_off();
              id(turnout_2_b).turn_on();
            }
        - delay: ${turnout_pulse_ms}
        - output.turn_off: turnout_2_a
        - output.turn_off: turnout_2_b
    # Turnout 3
    - topic: "track/turnout/TO-1-3"
      then:
        - lambda: |-
            auto payload = x.c_str();
            if (strcmp(payload, "THROWN") == 0) {
              id(turnout_3_a).turn_on();
              id(turnout_3_b).turn_off();
            } else if (strcmp(payload, "CLOSED") == 0) {
              id(turnout_3_a).turn_off();
              id(turnout_3_b).turn_on();
            }
        - delay: ${turnout_pulse_ms}
        - output.turn_off: turnout_3_a
        - output.turn_off: turnout_3_b
    # Turnout 4
    - topic: "track/turnout/TO-1-4"
      then:
        - lambda: |-
            auto payload = x.c_str();
            if (strcmp(payload, "THROWN") == 0) {
              id(turnout_4_a).turn_on();
              id(turnout_4_b).turn_off();
            } else if (strcmp(payload, "CLOSED") == 0) {
              id(turnout_4_a).turn_off();
              id(turnout_4_b).turn_on();
            }
        - delay: ${turnout_pulse_ms}
        - output.turn_off: turnout_4_a
        - output.turn_off: turnout_4_b
    # Turnout 5
    - topic: "track/turnout/TO-1-5"
      then:
        - lambda: |-
            auto payload = x.c_str();
            if (strcmp(payload, "THROWN") == 0) {
              id(turnout_5_a).turn_on();
              id(turnout_5_b).turn_off();
            } else if (strcmp(payload, "CLOSED") == 0) {
              id(turnout_5_a).turn_off();
              id(turnout_5_b).turn_on();
            }
        - delay: ${turnout_pulse_ms}
        - output.turn_off: turnout_5_a
        - output.turn_off: turnout_5_b
    # Turnout 6
    - topic: "track/turnout/TO-1-6"
      then:
        - lambda: |-
            auto payload = x.c_str();
            if (strcmp(payload, "THROWN") == 0) {
              id(turnout_6_a).turn_on();
              id(turnout_6_b).turn_off();
            } else if (strcmp(payload, "CLOSED") == 0) {
              id(turnout_6_a).turn_off();
              id(turnout_6_b).turn_on();
            }
        - delay: ${turnout_pulse_ms}
        - output.turn_off: turnout_6_a
        - output.turn_off: turnout_6_b
    # Turnout 7
    - topic: "track/turnout/TO-1-7"
      then:
        - lambda: |-
            auto payload = x.c_str();
            if (strcmp(payload, "THROWN") == 0) {
              id(turnout_7_a).turn_on();
              id(turnout_7_b).turn_off();
            } else if (strcmp(payload, "CLOSED") == 0) {
              id(turnout_7_a).turn_off();
              id(turnout_7_b).turn_on();
            }
        - delay: ${turnout_pulse_ms}
        - output.turn_off: turnout_7_a
        - output.turn_off: turnout_7_b
    # Turnout 8
    - topic: "track/turnout/TO-1-8"
      then:
        - lambda: |-
            auto payload = x.c_str();
            if (strcmp(payload, "THROWN") == 0) {
              id(turnout_8_a).turn_on();
              id(turnout_8_b).turn_off();
            } else if (strcmp(payload, "CLOSED") == 0) {
              id(turnout_8_a).turn_off();
              id(turnout_8_b).turn_on();
            }
        - delay: ${turnout_pulse_ms}
        - output.turn_off: turnout_8_a
        - output.turn_off: turnout_8_b

logger:
  level: DEBUG

captive_portal:

# Output pin mapping for each turnout coil (A/B)
output:
  - platform: gpio
    id: turnout_1_a
    pin: GPIO19
  - platform: gpio
    id: turnout_1_b
    pin: GPIO18

  - platform: gpio
    id: turnout_2_a
    pin: GPIO5
  - platform: gpio
    id: turnout_2_b
    pin: GPIO17

  - platform: gpio
    id: turnout_3_a
    pin: GPIO16
  - platform: gpio
    id: turnout_3_b
    pin: GPIO4

  - platform: gpio
    id: turnout_4_a
    pin: GPIO2
  - platform: gpio
    id: turnout_4_b
    pin: GPIO15

  - platform: gpio
    id: turnout_5_a
    pin: GPIO32
  - platform: gpio
    id: turnout_5_b
    pin: GPIO33

  - platform: gpio
    id: turnout_6_a
    pin: GPIO25
  - platform: gpio
    id: turnout_6_b
    pin: GPIO26

  - platform: gpio
    id: turnout_7_a
    pin: GPIO27
  - platform: gpio
    id: turnout_7_b
    pin: GPIO14

  - platform: gpio
    id: turnout_8_a
    pin: GPIO12
  - platform: gpio
    id: turnout_8_b
    pin: GPIO13
