# ESPHome YAML for HO Model Railroad Turnout Control with RC Servos
#
# This config controls N turnouts using RC servos on an ESP32.
# Each turnout has:
#   - A servo (see output/servo section for pin mapping)
#   - MQTT switch for JMRI or automation
#   - Angle slider and calibration buttons for Home Assistant
#   - Max/min angle variables (saved to flash)
#   - Sensors for current, max, and min angle (visible in Home Assistant)
#
# Hardware: ESP32 (32-pin), servos on recommended pins (see below)
#
# Usage:
#  - Use MQTT to throw/close turnouts (see switch section for topics)
#  - Use Home Assistant to calibrate and monitor angles
#
# Possible ESP32 pins for servos: 2, 4, 5, 12, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23, 25, 26, 27, 32, 33
# Avoid: 0, 1, 3, 6-11, 34-39
#
esphome:
  name: tc-servo
  friendly_name: TC-Servo

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "nDo0BcHsYs/IsNrF1JtHRrPNGzGAe0LxemlwVZoDN7k="

ota:
  - platform: esphome
    password: "bf1ded303b6bdaa4994bb0f7b9da76af"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Tc-Servo Fallback Hotspot"
    password: "iIDTqknPyamg"

captive_portal:

substitutions:
  controller_num: "1" # X in TOS-X-N
  num_turnouts: "2" # N = number of turnouts (change as needed)

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

# Example for 2 turnouts, add more as needed
# Each turnout has:
#   - A servo
#   - A switch (MQTT)
#   - Angle slider (Home Assistant)
#   - Set Max/Min buttons (Home Assistant)
#   - Max/Min angle variables (saved)
#   - Sensors for current/max/min angle

globals:
  - id: turnout_1_max_angle
    type: int
    restore_value: true
    initial_value: "180"
  - id: turnout_1_min_angle
    type: int
    restore_value: true
    initial_value: "0"
  - id: turnout_1_angle
    type: int
    restore_value: false
    initial_value: "90"
  - id: turnout_2_max_angle
    type: int
    restore_value: true
    initial_value: "180"
  - id: turnout_2_min_angle
    type: int
    restore_value: true
    initial_value: "0"
  - id: turnout_2_angle
    type: int
    restore_value: false
    initial_value: "90"

# Output pin mapping for each servo
output:
  - platform: ledc
    id: turnout_1_servo
    pin: 18
    frequency: 50 Hz
  - platform: ledc
    id: turnout_2_servo
    pin: 19
    frequency: 50 Hz

servo:
  - id: turnout_1
    output: turnout_1_servo
    min_level: 2.5%
    max_level: 12.5%
  - id: turnout_2
    output: turnout_2_servo
    min_level: 2.5%
    max_level: 12.5%

# MQTT switches and controls for each turnout
switch:
  - platform: template
    name: "TOS-${controller_num}-${num_turnouts} Turnout 1"
    id: turnout_1_switch
    optimistic: true
    restore_mode: ALWAYS_OFF
    turn_on_action:
      - lambda: |-
          id(turnout_1_angle) = id(turnout_1_max_angle);
          id(turnout_1).write(id(turnout_1_angle) / 180.0);
      - delay: 500ms
      - lambda: |-
          id(turnout_1).detach();
      - mqtt.publish:
          topic: "TOS-${controller_num}-${num_turnouts}/turnout_1/state"
          payload: "THROWN"
    turn_off_action:
      - lambda: |-
          id(turnout_1_angle) = id(turnout_1_min_angle);
          id(turnout_1).write(id(turnout_1_angle) / 180.0);
      - delay: 500ms
      - lambda: |-
          id(turnout_1).detach();
      - mqtt.publish:
          topic: "TOS-${controller_num}-${num_turnouts}/turnout_1/state"
          payload: "CLOSED"
    on_turn_on:
      - mqtt.publish:
          topic: "TOS-${controller_num}-${num_turnouts}/turnout_1/set"
          payload: "THROWN"
    on_turn_off:
      - mqtt.publish:
          topic: "TOS-${controller_num}-${num_turnouts}/turnout_1/set"
          payload: "CLOSED"
  - platform: template
    name: "TOS-${controller_num}-${num_turnouts} Turnout 2"
    id: turnout_2_switch
    optimistic: true
    restore_mode: ALWAYS_OFF
    turn_on_action:
      - lambda: |-
          id(turnout_2_angle) = id(turnout_2_max_angle);
          id(turnout_2).write(id(turnout_2_angle) / 180.0);
      - delay: 500ms
      - lambda: |-
          id(turnout_2).detach();
      - mqtt.publish:
          topic: "TOS-${controller_num}-${num_turnouts}/turnout_2/state"
          payload: "THROWN"
    turn_off_action:
      - lambda: |-
          id(turnout_2_angle) = id(turnout_2_min_angle);
          id(turnout_2).write(id(turnout_2_angle) / 180.0);
      - delay: 500ms
      - lambda: |-
          id(turnout_2).detach();
      - mqtt.publish:
          topic: "TOS-${controller_num}-${num_turnouts}/turnout_2/state"
          payload: "CLOSED"
    on_turn_on:
      - mqtt.publish:
          topic: "TOS-${controller_num}-${num_turnouts}/turnout_2/set"
          payload: "THROWN"
    on_turn_off:
      - mqtt.publish:
          topic: "TOS-${controller_num}-${num_turnouts}/turnout_2/set"
          payload: "CLOSED"

number:
  # Exposed to Home Assistant for calibration
  - platform: template
    name: "Turnout 1 Angle"
    id: turnout_1_angle_slider
    min_value: 0
    max_value: 180
    step: 1
    optimistic: true
    set_action:
      - lambda: |-
          id(turnout_1_angle) = x;
          id(turnout_1).write(x / 180.0);
      - delay: 500ms
      - lambda: |-
          id(turnout_1).detach();
  - platform: template
    name: "Turnout 2 Angle"
    id: turnout_2_angle_slider
    min_value: 0
    max_value: 180
    step: 1
    optimistic: true
    set_action:
      - lambda: |-
          id(turnout_2_angle) = x;
          id(turnout_2).write(x / 180.0);
      - delay: 500ms
      - lambda: |-
          id(turnout_2).detach();

button:
  # Exposed to Home Assistant for calibration
  - platform: template
    name: "Turnout 1 Set Max"
    on_press:
      - lambda: |-
          id(turnout_1_max_angle) = id(turnout_1_angle);
    icon: "mdi:arrow-up-bold"
  - platform: template
    name: "Turnout 1 Set Min"
    on_press:
      - lambda: |-
          id(turnout_1_min_angle) = id(turnout_1_angle);
    icon: "mdi:arrow-down-bold"
  - platform: template
    name: "Turnout 2 Set Max"
    on_press:
      - lambda: |-
          id(turnout_2_max_angle) = id(turnout_2_angle);
    icon: "mdi:arrow-up-bold"
  - platform: template
    name: "Turnout 2 Set Min"
    on_press:
      - lambda: |-
          id(turnout_2_min_angle) = id(turnout_2_angle);
    icon: "mdi:arrow-down-bold"

sensor:
  - platform: template
    name: "Turnout 1 Current Angle"
    id: turnout_1_current_angle_sensor
    lambda: |-
      return id(turnout_1_angle);
    update_interval: 1s
    unit_of_measurement: "°"
  - platform: template
    name: "Turnout 1 Max Angle"
    id: turnout_1_max_angle_sensor
    lambda: |-
      return id(turnout_1_max_angle);
    update_interval: 1s
    unit_of_measurement: "°"
  - platform: template
    name: "Turnout 1 Min Angle"
    id: turnout_1_min_angle_sensor
    lambda: |-
      return id(turnout_1_min_angle);
    update_interval: 1s
    unit_of_measurement: "°"
  - platform: template
    name: "Turnout 2 Current Angle"
    id: turnout_2_current_angle_sensor
    lambda: |-
      return id(turnout_2_angle);
    update_interval: 1s
    unit_of_measurement: "°"
  - platform: template
    name: "Turnout 2 Max Angle"
    id: turnout_2_max_angle_sensor
    lambda: |-
      return id(turnout_2_max_angle);
    update_interval: 1s
    unit_of_measurement: "°"
  - platform: template
    name: "Turnout 2 Min Angle"
    id: turnout_2_min_angle_sensor
    lambda: |-
      return id(turnout_2_min_angle);
    update_interval: 1s
    unit_of_measurement: "°"
# To add more turnouts, duplicate the relevant blocks and increment the numbers.
# All variables for max/min angles are saved to flash (restore_value: true).
# All MQTT topics are in the form TOS-X-N/turnout_N/set and TOS-X-N/turnout_N/state.
# You can control and calibrate via MQTT or Home Assistant dashboard.


